spring:
  config:
    activate:
      on-profile: qa
    import: optional:file:./envs/.env.qa

  # Database connection configuration
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:transformers}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL:10}
      minimum-idle: ${HIKARI_MIN_IDLE:5}
      connection-timeout: ${HIKARI_CONN_TIMEOUT:30000}

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # TODO: Add Kafka properties
  # TODO: Add PostgreSQL properties
  # TODO: Add actuator properties
  # TODO: Add flyway properties
  # TODO: Add OAuth for Keycloak
  # TODO: Add JPA properties
  # TODO: Compress data?

# Logging levels for the application
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:DEBUG}
    org.hibernate: ${LOG_LEVEL_HIBERNATE:INFO}

# Open API configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    supportedSubmitMethods: get, put, post, delete
  show-actuator: false
  auto-tag-classes: false
#  paths-to-exclude:
#  packages-to-exclude: